{{- if .Values.rabbitmqOperator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  labels:
    {{- include "ventros-crm.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  labels:
    {{- include "ventros-crm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  - rabbitmqclusters/status
  - rabbitmqclusters/finalizers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  labels:
    {{- include "ventros-crm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
subjects:
- kind: ServiceAccount
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  labels:
    {{- include "ventros-crm.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ventros-crm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq-operator
  template:
    metadata:
      labels:
        {{- include "ventros-crm.labels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq-operator
    spec:
      serviceAccountName: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
      containers:
      - name: operator
        image: {{ .Values.rabbitmqOperator.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.rabbitmqOperator.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ventros-crm.fullname" . }}-rabbitmq-operator
  labels:
    {{- include "ventros-crm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9782
    name: metrics
    protocol: TCP
    targetPort: 9782
  selector:
    {{- include "ventros-crm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq-operator
{{- end }}
