version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ventros-postgres-dev
    environment:
      POSTGRES_USER: ventros
      POSTGRES_PASSWORD: ventros123
      POSTGRES_DB: ventros_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ventros"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-dev-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ventros-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-dev-network

  redis:
    image: redis:7-alpine
    container_name: ventros-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-dev-network

  temporal:
    image: temporalio/auto-setup:1.24.2
    container_name: ventros-temporal-dev
    environment:
      - DB=postgres12_pgx
      - DB_PORT=5432
      - POSTGRES_USER=ventros
      - POSTGRES_PWD=ventros123
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233"
    volumes:
      - temporal_dev_data:/etc/temporal
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-dev-network

  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: ventros-temporal-ui-dev
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8088:8080"
    depends_on:
      - temporal
    networks:
      - ventros-dev-network

volumes:
  postgres_dev_data:
    driver: local
  rabbitmq_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  temporal_dev_data:
    driver: local

networks:
  ventros-dev-network:
    driver: bridge
