version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ventros-postgres
    environment:
      POSTGRES_USER: ventros
      POSTGRES_PASSWORD: ventros123
      POSTGRES_DB: ventros_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ventros"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ventros-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: ventros-api
    environment:
      PORT: 8080
      ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ventros
      DB_PASSWORD: ventros123
      DB_NAME: ventros_crm
      DB_SSLMODE: disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - ventros-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  ventros-network:
    driver: bridge
