version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ventros-postgres
    environment:
      POSTGRES_USER: ventros
      POSTGRES_PASSWORD: ventros123
      POSTGRES_DB: ventros_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ventros"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ventros-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  redis:
    image: redis:7-alpine
    container_name: ventros-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  temporal:
    image: temporalio/auto-setup:1.24.2
    container_name: ventros-temporal
    environment:
      - DB=postgres12_pgx
      - DB_PORT=5432
      - POSTGRES_USER=ventros
      - POSTGRES_PWD=ventros123
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233"
    volumes:
      - temporal_data:/etc/temporal
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ventros-network

  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: ventros-temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8088:8080"
    depends_on:
      - temporal
    networks:
      - ventros-network

  api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: ventros-api
    environment:
      PORT: 8080
      ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ventros
      DB_PASSWORD: ventros123
      DB_NAME: ventros_crm
      DB_SSLMODE: disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      TEMPORAL_HOST: temporal:7233
      TEMPORAL_NAMESPACE: default
      LOG_LEVEL: info
      ADMIN_EMAIL: admin@ventros.com
      ADMIN_PASSWORD: admin123
      ADMIN_NAME: Administrator
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      temporal:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - ventros-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  temporal_data:
    driver: local

networks:
  ventros-network:
    driver: bridge
